name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          service_account: github-addi-nonprod@central-workload-identity-f740.iam.gserviceaccount.com
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          allow_unauthenticated: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/addi-demo-ar/myapp:${{ github.sha }} .

      - name: Configure Docker to authenticate with Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT }}.appspot.com

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/addi-demo-ar/myapp:${{ github.sha }}
