name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

env:
  PROJECT_ID: addi-demo-bdbf
  GAR_LOCATION: us-west1
  REGION: us-west1
  REPOSITORY: addi-demo-ar
  WORKLOAD_IDENTITY_PROVIDER: "projects/361994530756/locations/global/workloadIdentityPools/github/providers/github"
  SERVICE_ACCOUNT: github-addi-nonprod@central-workload-identity-f740.iam.gserviceaccount.com
  ENV_NAME: prod

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Authenticate with Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: "Build-and-Push_to_Artifact_registy"
        name: Build and push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
            context: ./
            build-args: |
              "GCP_PROJECT_ID=${{ env.PROJECT_ID}}"
            file: ./Dockerfile
            push: true
            tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/myapp:latest
  
      - id: "Deploy"
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: myapp
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/myapp:latest
          project_id: addi-demo-bdbf
          flags: "--service-account=github-addi-nonprod@central-workload-identity-f740.iam.gserviceaccount.com --ingress=internal-and-cloud-load-balancing"
