name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Adding private SSH key to ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GCP_DEV_SSH_PRIVATE_KEY }}"

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Go project
        run: GOOS=linux GOARCH=amd64 go build -o my-binary

      - name: scp binary to GCE and apply latest version
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r my-binary ${{ secrets.GCP_DEV_VM_USER }}@${{ secrets.GCP_DEV_VM_IP }}:./my-binary.new
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_DEV_VM_USER }}@${{ secrets.GCP_DEV_VM_IP }} << 'ENDSSH'
            echo "** restarting service tof apply new version **"
            sudo service my-binary stop
            echo "** service stopped **"
            mv my-binary.new my-binary
            chmod +x my-binary
            sudo service my-binary start
            echo "** service started **"
            ps -ef |grep my-binary
          ENDSSH          

      - name: Clean up
        run: rm -f gcp_key addi-server
