name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v2.1.4
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "gcloud-service-key.json"
          gcloud auth activate-service-account --key-file="gcloud-service-key.json"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/addi-demo-ar/myapp:${{ github.sha }} .

      - name: Configure Docker to authenticate with Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT }}.appspot.com

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/addi-demo-ar/myapp:${{ github.sha }}
