name: Deploy to Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: addi-demo-bdbf
  GAR_LOCATION: us-west1
  GAR_SERVICE: addi-server-demo
  REGION: us-west1
  REPOSITORY: addi-demo-ar
  WORKLOAD_IDENTITY_PROVIDER: "projects/514928924151/locations/global/workloadIdentityPools/github/providers/gtihub"
  SERVICE_ACCOUNT: github-addi-nonprod1@addi-demo-bdbf.iam.gserviceaccount.com
  ENV_NAME: prod
  VM_INSTANCE_NAME: addi-srv-demo
  VM_ZONE: us-east4-b  # Adjust the VM zone to match your actual zone
  VM_SSH_KEY_PATH: /path/to/ssh/ke

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Authenticate with Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - id: ssh
        name: SSH into VM and run pull latest Docker image script
        run: |
          echo "Setting up SSH connection to VM"
          gcloud compute ssh ${{ env.VM_INSTANCE_NAME }} \
            --zone ${{ env.VM_ZONE }} \
            --project ${{ env.PROJECT_ID }} \
            --ssh-key-file=${{ env.VM_SSH_KEY_PATH }} \
            --command="bash /path/to/your/script.sh"  # Replace with actual path to your script


      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: us-west1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      # - id: "Build-and-Push_to_Artifact_registy"
      #   name: Build and push Docker image to Google Artifact Registry
      #   uses: docker/build-push-action@v3
      #   with:
      #       context: ./
      #       build-args: |
      #         "GCP_PROJECT_ID=${{ env.PROJECT_ID}}"
      #       file: ./Dockerfile
      #       push: true
      #       tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.GAR_SERVICE }}:latest
  
      # - id: "Deploy"
      #   name: Deploy to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v1
      #   with:
      #     service: ${{ env.GAR_SERVICE }}
      #     region: ${{ env.REGION }}
      #     image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.GAR_SERVICE }}:latest
      #     project_id: ${{ env.PROJECT_ID }}
      #     flags: "--service-account=github-addi-nonprod1@addi-demo-bdbf.iam.gserviceaccount.com"

      # - id: "GetURL"
      #   name: Get the Cloud Run URL
      #   run: |
      #     SERVICE_URL=$(gcloud run services describe ${{ env.GAR_SERVICE }} --region ${{ env.REGION }} --platform managed --project ${{ env.PROJECT_ID }} --format "value(status.url)")
      #     echo "Deployed Cloud Run URL: $SERVICE_URL"